---
- hosts: all
  tasks:
    - debug:
        msg: play1
- name: Deploy webservers in u1, u2 and u3
  import_playbook: tasks/webservers.yaml
- name: Deploy Databases in u3
  import_playbook: tasks/databases.yaml
...

